CREATE TABLE Movie(id INT PRIMARY KEY, title VARCHAR(100) NOT NULL, year INT, rating VARCHAR(10), company VARCHAR(50)
)ENGINE = INNODB;

CREATE TABLE Actor(id INT PRIMARY KEY, last VARCHAR(20) NOT NULL, first VARCHAR(20) NOT NULL, sex VARCHAR(6), 
dob DATE NOT NULL, dod DATE
)ENGINE = INNODB;

CREATE TABLE Director(id INT PRIMARY KEY, last VARCHAR(20) NOT NULL, first VARCHAR(20) NOT NULL, dob DATE NOT NULL, 
dod DATE)ENGINE = INNODB;

CREATE TABLE MovieGenre(mid INT, genre VARCHAR(20) NOT NULL,
FOREIGN KEY (mid) references Movie(id)
)ENGINE = INNODB;

CREATE TABLE MovieDirector(mid INT, did INT,
FOREIGN KEY (did) references Director(id),
FOREIGN KEY (mid) references Movie(id)
)ENGINE = INNODB;

CREATE TABLE MovieActor(mid INT, aid INT, role VARCHAR(50) NOT NULL,
FOREIGN KEY (aid) references Actor(id),
FOREIGN KEY (mid) references Movie(id)
)ENGINE = INNODB;

CREATE TABLE Review(name VARCHAR(20) NOT NULL, time TIMESTAMP, mid INT NOT NULL, rating INT NOT NULL, comment VARCHAR(500),
FOREIGN KEY (mid) references Movie(id)
)ENGINE = INNODB;

CREATE TABLE MaxPersonID(id INT)ENGINE = INNODB;
CREATE TABLE MaxMovieID(id INT)ENGINE = INNODB;

INSERT INTO MaxPersonID VALUES (69000);
INSERT INTO MaxMovieID VALUES (4750);