CREATE TABLE Movie(id INT PRIMARY KEY, title VARCHAR(100) NOT NULL, year INT, rating VARCHAR(10), company VARCHAR(50)
)ENGINE = INNODB;
CREATE TABLE Actor(id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), sex VARCHAR(6), 
dob DATE NOT NULL, dod DATE)ENGINE = INNODB;
CREATE TABLE Director(id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), dob DATE, 
dod DATE)ENGINE = INNODB;
CREATE TABLE MovieGenre(mid INT, genre VARCHAR(20))ENGINE = INNODB;
CREATE TABLE MovieDirector(mid INT, did INT)ENGINE = INNODB;
CREATE TABLE MovieActor(mid INT, aid INT, role VARCHAR(50))ENGINE = INNODB;
CREATE TABLE Review(name VARCHAR(20) NOT NULL, time TIMESTAMP, mid INT NOT NULL, rating INT NOT NULL, comment VARCHAR(500),
CHECK (rating BETWEEN 1 and 5),
CHECK (mid > 0)
)ENGINE = INNODB;
CREATE TABLE MaxPersonID(id INT)ENGINE = INNODB;
CREATE TABLE MaxMovieID(id INT)ENGINE = INNODB;
INSERT INTO MaxPersonID VALUES (69000);
INSERT INTO MaxMovieID VALUES (4750);